---

- name: RouterOS test with network_cli connection
  hosts: mikrotik
  gather_facts: false
  tasks:

  - name: Gather facts
    community.routeros.facts:

  - name: Show a fact
    debug:
      msg: "First IP address: {{ ansible_net_all_ipv4_addresses[0] }}"
