---

- name: RouterOS test
  hosts: mikrotik
  connection: network_cli
  vars:
    ansible_network_os: routeros
    ansible_user: admin
  gather_facts: false
  tasks:

  - name: Gather facts
    community.routeros.facts:

  - name: Show a fact
    debug:
      msg: "First IP address: {{ ansible_net_all_ipv4_addresses[0] }}"
