---
- name: Update packages on Ubuntu hosts
  hosts: ubuntu
  gather_facts: false

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Upgrade packages
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
